# Generated by Django 3.2 on 2022-03-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_votes_count_reply_votes_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='downvoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='upvoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='downvoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='upvoted',
            field=models.BooleanField(default=False),
        ),
    ]
